import runDimDemo from "./dimDemo";
import runNoteDemo from "./noteDemo";
import runBorderDemo from "./borderDemo";
import runUshellDemo from "./ushellDemo";
import runFrameSingleDemo from "./frameSingleDemo";
import runPileDemo from "./pileDemo";
import runFrameDoubleDemo from "./frameDoubleDemo";
import runPlatformDemo from "./platformDemo";
import runDXFDemo from "./dxfDemo";

console.time();
// runDimDemo();
// runNoteDemo();
// runBorderDemo();
// runUshellDemo();
// runFrameSingleDemo();
// runFrameDoubleDemo();
// runPileDemo();
runPlatformDemo();
// runDXFDemo();
console.timeEnd();