import runDimDemo from "./dimDemo";
import runBorderDemo from "./borderDemo";
import runUshellDemo from "./ushellDemo";
import runFrameSingleDemo from "./frameSingleDemo";
import runPileDemo from "./pileDemo";
import runFrameDoubleDemo from "./frameDoubleDemo";
import runPlatformDemo from "./platformDemo";
import runDXFDemo from "./dxfDemo";
import runFrameSingleTopDemo from "./frameSingleTopDemo";
import runPierSolidDemo from "./pierSolidDemo";
import runFoundDemo from "./foundDemo";
import runFrameSingleTopDemo2 from "./frameSingleTopDemo2";
import runFrameSingleDemoBaiyandong from "./frameSingleDemoBaiyandong";
import runPileDemoBaiyandong from "./pileDemoBaiyandong";
import runPlatformDemoBaiyandong from "./platformDemoBaiyandong";
import runPierHollowDemo from "./pierHollowDemo";
import runPierSolidDemoDongGan from "./pierSolidDemoDongGan";
import runPileDemoMaolicao from "./pileDemoMaolicao";
import runPileDemoFengXingLing from "./pileDemoFengXingLing";
import runPierSolidDemoFengXingLing from "./pierSolidDemoFengXingLing";

console.time();
// runDimDemo();
// runBorderDemo();
// runUshellDemo();
// runFrameSingleDemo();
// runFrameSingleDemoBaiyandong();
// runFrameSingleTopDemo();
// runFrameSingleTopDemo2();
// runFrameDoubleDemo();
// runPileDemo();
// runPileDemoBaiyandong();
// runPileDemoMaolicao();
// runPileDemoFengXingLing();
// runPlatformDemo();
// runPlatformDemoBaiyandong();
// runPierSolidDemo();
// runPierSolidDemoDongGan();
// runPierSolidDemoFengXingLing();
// runPierHollowDemo();
// runFoundDemo();
// runDXFDemo();
console.timeEnd();